spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/fly_jpa"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
#        cache:
#          use_second_level_cache: false
#          use_query_cache: false
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
