version: '3'
services:
  db:
    container_name: fly-jpa-postgres
    image: postgres:14.7-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fly_jpa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fly-jpa-postgres-data:/var/lib/postgresql/data
    networks:
      - fly-jpa-network

networks:
  fly-jpa-network:
    driver: bridge

volumes:
  fly-jpa-postgres-data:
    driver: local
